baseURL = "https://alyosha-swamy.github.io/"
languageCode = "en-us"
title = "Tensoic - AI Model Solutions for Enterprise"
theme = "tensoic"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "Models"
    url = "/models/"
    weight = 3
